---
version: '3.8'

volumes:
  node_modules:
  sharedstreets-cache:


services:
  sharedstreetsjs:
    build: .
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      - sharedstreets-cache:/home/node/.shst
      - $HOME/Data:/home/node/data
